### ISSUE TITLE
Skeleton enable/disable doesn't work.

### ISSUE THREAD

**Issue by Claycorp** [Kashdeya/Knob-Control#4]
I have all the hostile mobs turned off and was trying to only get endermen spawning. Currently skeletons and endermen spawn. Even though skeletons are off. This is the only mod running thus no other mod is interfering with it.

Config: http://pastebin.com/vfzs4uv6
Loaded Mods: http://i.imgur.com/kOx1MQn.png
FML log: http://pastebin.com/FFtaLwXH
Millions of skeletons, Skeletons for free: http://i.imgur.com/nYVurrA.png

**Comment by Kashdeya** [comment]
I will look into this after xmas Clay. Send me a pm on curse to remind me please.

**Comment by Claycorp** [comment]
Not a problem

**Comment by Kashdeya** [comment]
@Claycorp this problem has been fixed and will be in the next update.
